### PR TITLE
251 filtered headers dont persist

### PR DESCRIPTION
**Pull request by OsamaMSoliman**

### CODE REVIEW

**Review by vijulshah — COMMENTED** [review]
Found one bug:
I filtered some columns via checkboxes and then navigated to one of the experiments. Then I came back and filtered columns via text search. This time the columns are getting filtered but the checkboxes of the previously selected columns are still checked.

**Comment by OsamaMSoliman** [comment]
@vijulshah can you check again please!

**Comment by vijulshah** [comment]
@OsamaMSoliman  Yes, I checked. Everything looks good now!

**Comment by OsamaMSoliman** [comment]
following the rebase workflow:
locally on dev:
git pull dev
git switch 251-filtered-headers-dont-persist
git pull 251-filtered-headers-dont-persist
git rebase dev
git push (this throws an error, because of changed history, so --force is needed to rewrite the history)
git push --force
git switch dev
git merge 251-filtered-headers-dont-persist
git push

**Pull request merged**
